// Generated by CoffeeScript 1.6.3
(function() {
  var MoreAnalyticsL10N;

  jQuery.MoreAnalyticsL10N = MoreAnalyticsL10N = (function() {
    function MoreAnalyticsL10N() {}

    MoreAnalyticsL10N.lexicon = {
      metrics: {
        abandonedFunnels: {
          l: 'Abandoned Funnels',
          g: 'Other'
        },
        abandonedFunnels1: {
          l: 'Goal 1 (Goal 1 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels10: {
          l: 'Goal 10 (Goal 10 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels11: {
          l: 'Goal 11 (Goal 11 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels12: {
          l: 'Goal 12 (Goal 12 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels13: {
          l: 'Goal 13 (Goal 13 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels14: {
          l: 'Goal 14 (Goal 14 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels15: {
          l: 'Goal 15 (Goal 15 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels16: {
          l: 'Goal 16 (Goal 16 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels17: {
          l: 'Goal 17 (Goal 17 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels18: {
          l: 'Goal 18 (Goal 18 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels19: {
          l: 'Goal 19 (Goal 19 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels2: {
          l: 'Goal 2 (Goal 2 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels20: {
          l: 'Goal 20 (Goal 20 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels3: {
          l: 'Goal 3 (Goal 3 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels4: {
          l: 'Goal 4 (Goal 4 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels5: {
          l: 'Goal 5 (Goal 5 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels6: {
          l: 'Goal 6 (Goal 6 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels7: {
          l: 'Goal 7 (Goal 7 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels8: {
          l: 'Goal 8 (Goal 8 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnels9: {
          l: 'Goal 9 (Goal 9 Abandoned Funnels)',
          g: 'Other'
        },
        abandonedFunnelsRate: {
          l: 'Total Abandonment Rate',
          g: 'Other'
        },
        abandonedFunnelsRate1: {
          l: 'Goal 1 (Goal 1 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate10: {
          l: 'Goal 10 (Goal 10 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate11: {
          l: 'Goal 11 (Goal 11 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate12: {
          l: 'Goal 12 (Goal 12 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate13: {
          l: 'Goal 13 (Goal 13 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate14: {
          l: 'Goal 14 (Goal 14 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate15: {
          l: 'Goal 15 (Goal 15 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate16: {
          l: 'Goal 16 (Goal 16 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate17: {
          l: 'Goal 17 (Goal 17 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate18: {
          l: 'Goal 18 (Goal 18 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate19: {
          l: 'Goal 19 (Goal 19 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate2: {
          l: 'Goal 2 (Goal 2 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate20: {
          l: 'Goal 20 (Goal 20 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate3: {
          l: 'Goal 3 (Goal 3 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate4: {
          l: 'Goal 4 (Goal 4 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate5: {
          l: 'Goal 5 (Goal 5 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate6: {
          l: 'Goal 6 (Goal 6 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate7: {
          l: 'Goal 7 (Goal 7 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate8: {
          l: 'Goal 8 (Goal 8 Abandonment Rate)',
          g: 'Other'
        },
        abandonedFunnelsRate9: {
          l: 'Goal 9 (Goal 9 Abandonment Rate)',
          g: 'Other'
        },
        adsenseAdUnitsViewed: {
          l: 'AdSense Ad Units Viewed',
          g: 'Advertising'
        },
        adsenseAdsClicked: {
          l: 'AdSense Ads Clicked',
          g: 'Advertising'
        },
        adsenseCTR: {
          l: 'AdSense CTR',
          g: 'Advertising'
        },
        adsenseECPM: {
          l: 'AdSense eCPM',
          g: 'Advertising'
        },
        adsenseExits: {
          l: 'AdSense Exits',
          g: 'Advertising'
        },
        adsensePageImpressions: {
          l: 'AdSense Page Impressions',
          g: 'Advertising'
        },
        adsenseRevenue: {
          l: 'AdSense Revenue',
          g: 'Advertising'
        },
        adsenseUnitImpressions: {
          l: 'AdSense Ads Viewed',
          g: 'Advertising'
        },
        appviews: {
          l: 'Screen Views',
          g: 'Visitors'
        },
        avgAppviewDuration: {
          l: 'Avg. Time on Screen',
          g: 'Visitors'
        },
        avgAppviews: {
          l: 'Screens / Session',
          g: 'Visitors'
        },
        avgDomContentLoadedTime: {
          l: 'Avg. Document Content Loaded Time (sec)',
          g: 'Content'
        },
        avgDomInteractiveTime: {
          l: 'Avg. Document Interactive Time (sec)',
          g: 'Content'
        },
        avgDomainLookupTime: {
          l: 'Avg. Domain Lookup Time (sec)',
          g: 'Content'
        },
        avgPageDownloadTime: {
          l: 'Avg. Page Download Time (sec)',
          g: 'Content'
        },
        avgPageDuration: {
          l: 'Avg. Time on Page',
          g: 'Visitors'
        },
        avgPageLoadTime: {
          l: 'Avg. Page Load Time (sec)',
          g: 'Content'
        },
        avgPageviews: {
          l: 'Pages / Visit',
          g: 'Visitors'
        },
        avgRedirectionTime: {
          l: 'Avg. Redirection Time (sec)',
          g: 'Content'
        },
        avgServerConnectionTime: {
          l: 'Avg. Server Connection Time (sec)',
          g: 'Content'
        },
        avgServerResponseTime: {
          l: 'Avg. Server Response Time (sec)',
          g: 'Content'
        },
        avgSessionTime: {
          l: 'Avg. Visit Duration',
          g: 'Visitors'
        },
        avgUserTiming: {
          l: 'Avg. User Timing (sec)',
          g: 'Content'
        },
        bounceRate: {
          l: 'Bounce Rate',
          g: 'Visitors'
        },
        bounces: {
          l: 'Bounces',
          g: 'Visitors'
        },
        domLatencyMetricsCount: {
          l: 'DOM Latency Metrics Sample',
          g: 'Content'
        },
        domainLookupTimeCount: {
          l: 'Domain Lookup Sample',
          g: 'Content'
        },
        entranceRate: {
          l: 'Entrances / Pageviews',
          g: 'Content'
        },
        entrances: {
          l: 'Entrances',
          g: 'Content'
        },
        exitRate: {
          l: '% Exit',
          g: 'Visitors'
        },
        exits: {
          l: 'Exits',
          g: 'Visitors'
        },
        goal10Completions: {
          l: 'Goal 10 (Goal 10 Completions)',
          g: 'Conversions'
        },
        goal10Starts: {
          l: 'Goal 10 (Goal 10 Starts)',
          g: 'Conversions'
        },
        goal10Value: {
          l: 'Goal 10 (Goal 10 Value)',
          g: 'Conversions'
        },
        goal11Completions: {
          l: 'Goal 11 (Goal 11 Completions)',
          g: 'Conversions'
        },
        goal11Starts: {
          l: 'Goal 11 (Goal 11 Starts)',
          g: 'Conversions'
        },
        goal11Value: {
          l: 'Goal 11 (Goal 11 Value)',
          g: 'Conversions'
        },
        goal12Completions: {
          l: 'Goal 12 (Goal 12 Completions)',
          g: 'Conversions'
        },
        goal12Starts: {
          l: 'Goal 12 (Goal 12 Starts)',
          g: 'Conversions'
        },
        goal12Value: {
          l: 'Goal 12 (Goal 12 Value)',
          g: 'Conversions'
        },
        goal13Completions: {
          l: 'Goal 13 (Goal 13 Completions)',
          g: 'Conversions'
        },
        goal13Starts: {
          l: 'Goal 13 (Goal 13 Starts)',
          g: 'Conversions'
        },
        goal13Value: {
          l: 'Goal 13 (Goal 13 Value)',
          g: 'Conversions'
        },
        goal14Completions: {
          l: 'Goal 14 (Goal 14 Completions)',
          g: 'Conversions'
        },
        goal14Starts: {
          l: 'Goal 14 (Goal 14 Starts)',
          g: 'Conversions'
        },
        goal14Value: {
          l: 'Goal 14 (Goal 14 Value)',
          g: 'Conversions'
        },
        goal15Completions: {
          l: 'Goal 15 (Goal 15 Completions)',
          g: 'Conversions'
        },
        goal15Starts: {
          l: 'Goal 15 (Goal 15 Starts)',
          g: 'Conversions'
        },
        goal15Value: {
          l: 'Goal 15 (Goal 15 Value)',
          g: 'Conversions'
        },
        goal16Completions: {
          l: 'Goal 16 (Goal 16 Completions)',
          g: 'Conversions'
        },
        goal16Starts: {
          l: 'Goal 16 (Goal 16 Starts)',
          g: 'Conversions'
        },
        goal16Value: {
          l: 'Goal 16 (Goal 16 Value)',
          g: 'Conversions'
        },
        goal17Completions: {
          l: 'Goal 17 (Goal 17 Completions)',
          g: 'Conversions'
        },
        goal17Starts: {
          l: 'Goal 17 (Goal 17 Starts)',
          g: 'Conversions'
        },
        goal17Value: {
          l: 'Goal 17 (Goal 17 Value)',
          g: 'Conversions'
        },
        goal18Completions: {
          l: 'Goal 18 (Goal 18 Completions)',
          g: 'Conversions'
        },
        goal18Starts: {
          l: 'Goal 18 (Goal 18 Starts)',
          g: 'Conversions'
        },
        goal18Value: {
          l: 'Goal 18 (Goal 18 Value)',
          g: 'Conversions'
        },
        goal19Completions: {
          l: 'Goal 19 (Goal 19 Completions)',
          g: 'Conversions'
        },
        goal19Starts: {
          l: 'Goal 19 (Goal 19 Starts)',
          g: 'Conversions'
        },
        goal19Value: {
          l: 'Goal 19 (Goal 19 Value)',
          g: 'Conversions'
        },
        goal1Completions: {
          l: 'Goal 1 (Goal 1 Completions)',
          g: 'Conversions'
        },
        goal1Starts: {
          l: 'Goal 1 (Goal 1 Starts)',
          g: 'Conversions'
        },
        goal1Value: {
          l: 'Goal 1 (Goal 1 Value)',
          g: 'Conversions'
        },
        goal20Completions: {
          l: 'Goal 20 (Goal 20 Completions)',
          g: 'Conversions'
        },
        goal20Starts: {
          l: 'Goal 20 (Goal 20 Starts)',
          g: 'Conversions'
        },
        goal20Value: {
          l: 'Goal 20 (Goal 20 Value)',
          g: 'Conversions'
        },
        goal2Completions: {
          l: 'Goal 2 (Goal 2 Completions)',
          g: 'Conversions'
        },
        goal2Starts: {
          l: 'Goal 2 (Goal 2 Starts)',
          g: 'Conversions'
        },
        goal2Value: {
          l: 'Goal 2 (Goal 2 Value)',
          g: 'Conversions'
        },
        goal3Completions: {
          l: 'Goal 3 (Goal 3 Completions)',
          g: 'Conversions'
        },
        goal3Starts: {
          l: 'Goal 3 (Goal 3 Starts)',
          g: 'Conversions'
        },
        goal3Value: {
          l: 'Goal 3 (Goal 3 Value)',
          g: 'Conversions'
        },
        goal4Completions: {
          l: 'Goal 4 (Goal 4 Completions)',
          g: 'Conversions'
        },
        goal4Starts: {
          l: 'Goal 4 (Goal 4 Starts)',
          g: 'Conversions'
        },
        goal4Value: {
          l: 'Goal 4 (Goal 4 Value)',
          g: 'Conversions'
        },
        goal5Completions: {
          l: 'Goal 5 (Goal 5 Completions)',
          g: 'Conversions'
        },
        goal5Starts: {
          l: 'Goal 5 (Goal 5 Starts)',
          g: 'Conversions'
        },
        goal5Value: {
          l: 'Goal 5 (Goal 5 Value)',
          g: 'Conversions'
        },
        goal6Completions: {
          l: 'Goal 6 (Goal 6 Completions)',
          g: 'Conversions'
        },
        goal6Starts: {
          l: 'Goal 6 (Goal 6 Starts)',
          g: 'Conversions'
        },
        goal6Value: {
          l: 'Goal 6 (Goal 6 Value)',
          g: 'Conversions'
        },
        goal7Completions: {
          l: 'Goal 7 (Goal 7 Completions)',
          g: 'Conversions'
        },
        goal7Starts: {
          l: 'Goal 7 (Goal 7 Starts)',
          g: 'Conversions'
        },
        goal7Value: {
          l: 'Goal 7 (Goal 7 Value)',
          g: 'Conversions'
        },
        goal8Completions: {
          l: 'Goal 8 (Goal 8 Completions)',
          g: 'Conversions'
        },
        goal8Starts: {
          l: 'Goal 8 (Goal 8 Starts)',
          g: 'Conversions'
        },
        goal8Value: {
          l: 'Goal 8 (Goal 8 Value)',
          g: 'Conversions'
        },
        goal9Completions: {
          l: 'Goal 9 (Goal 9 Completions)',
          g: 'Conversions'
        },
        goal9Starts: {
          l: 'Goal 9 (Goal 9 Starts)',
          g: 'Conversions'
        },
        goal9Value: {
          l: 'Goal 9 (Goal 9 Value)',
          g: 'Conversions'
        },
        goalCompletionsAll: {
          l: 'Goal Completions',
          g: 'Conversions'
        },
        goalConversionRate: {
          l: 'Goal Conversion Rate',
          g: 'Conversions'
        },
        goalConversionRate1: {
          l: 'Goal 1 (Goal 1 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate10: {
          l: 'Goal 10 (Goal 10 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate11: {
          l: 'Goal 11 (Goal 11 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate12: {
          l: 'Goal 12 (Goal 12 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate13: {
          l: 'Goal 13 (Goal 13 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate14: {
          l: 'Goal 14 (Goal 14 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate15: {
          l: 'Goal 15 (Goal 15 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate16: {
          l: 'Goal 16 (Goal 16 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate17: {
          l: 'Goal 17 (Goal 17 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate18: {
          l: 'Goal 18 (Goal 18 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate19: {
          l: 'Goal 19 (Goal 19 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate2: {
          l: 'Goal 2 (Goal 2 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate20: {
          l: 'Goal 20 (Goal 20 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate3: {
          l: 'Goal 3 (Goal 3 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate4: {
          l: 'Goal 4 (Goal 4 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate5: {
          l: 'Goal 5 (Goal 5 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate6: {
          l: 'Goal 6 (Goal 6 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate7: {
          l: 'Goal 7 (Goal 7 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate8: {
          l: 'Goal 8 (Goal 8 Conversion Rate)',
          g: 'Conversions'
        },
        goalConversionRate9: {
          l: 'Goal 9 (Goal 9 Conversion Rate)',
          g: 'Conversions'
        },
        goalStartsAll: {
          l: 'Goal Starts',
          g: 'Conversions'
        },
        goalValueAll: {
          l: 'Goal Value',
          g: 'Conversions'
        },
        goalValuePerVisit: {
          l: 'Per Visit Goal Value',
          g: 'Conversions'
        },
        itemLocalRevenue: {
          l: 'Local Product Revenue',
          g: 'Conversions'
        },
        itemQuantity: {
          l: 'Quantity',
          g: 'Conversions'
        },
        itemRevenue: {
          l: 'Product Revenue',
          g: 'Conversions'
        },
        latencyMetricsCount: {
          l: 'Speed Metrics Sample',
          g: 'Content'
        },
        margin: {
          l: 'Margin',
          g: 'Advertising'
        },
        newVisits: {
          l: 'New Visits',
          g: 'Visitors'
        },
        pageDownloadTimeCount: {
          l: 'Page Download Sample',
          g: 'Content'
        },
        pageLoadTimeCount: {
          l: 'Page Load Sample',
          g: 'Content'
        },
        pageValue: {
          l: 'Page Value',
          g: 'Conversions'
        },
        pageviews: {
          l: 'Pageviews',
          g: 'Visitors'
        },
        pageviewsPerSearch: {
          l: 'Results Pageviews / Search',
          g: 'Visitors'
        },
        percentNewVisits: {
          l: '% New Visits',
          g: 'Visitors'
        },
        percentSearchExits: {
          l: '% Search Exits',
          g: 'Visitors'
        },
        percentSearchRefinements: {
          l: '% Search Refinements',
          g: 'Visitors'
        },
        productRevenuePerProducts: {
          l: 'Average Price',
          g: 'Conversions'
        },
        productsPerProductPurchases: {
          l: 'Average QTY',
          g: 'Conversions'
        },
        redirectionTimeCount: {
          l: 'Redirection Sample',
          g: 'Content'
        },
        returnOnInvestment: {
          l: 'ROI',
          g: 'Advertising'
        },
        revenuePerClick: {
          l: 'RPC',
          g: 'Advertising'
        },
        revenuePerTransaction: {
          l: 'Average Value',
          g: 'Conversions'
        },
        revenuePerVisit: {
          l: 'Per Visit Value',
          g: 'Conversions'
        },
        searchDepth: {
          l: 'Search Depth',
          g: 'Content'
        },
        searchDuration: {
          l: 'Time after Search',
          g: 'Content'
        },
        searchExits: {
          l: 'Search Exits',
          g: 'Content'
        },
        searchRefinements: {
          l: 'Search Refinements',
          g: 'Content'
        },
        searchUniques: {
          l: 'Total Unique Searches',
          g: 'Visitors'
        },
        searchVisits: {
          l: 'Visits with Search',
          g: 'Content'
        },
        serverConnectionTimeCount: {
          l: 'Server Connection Sample',
          g: 'Content'
        },
        serverResponseTimeCount: {
          l: 'Server Response Sample',
          g: 'Content'
        },
        socialInteractions: {
          l: 'Social Actions',
          g: 'Social'
        },
        socialInteractionsPerVisit: {
          l: 'Actions Per Social Visit',
          g: 'Social'
        },
        timeOnAppview: {
          l: 'Time on Screen',
          g: 'Content'
        },
        timeOnPage: {
          l: 'Time on Page',
          g: 'Content'
        },
        timeOnSite: {
          l: 'Visit Duration',
          g: 'Visitors'
        },
        totalVisitors: {
          l: 'Unique Visitors',
          g: 'Visitors'
        },
        transactionLocalRevenue: {
          l: 'Local Revenue',
          g: 'Conversions'
        },
        transactionLocalShipping: {
          l: 'Local Shipping',
          g: 'Conversions'
        },
        transactionLocalTax: {
          l: 'Local Tax',
          g: 'Conversions'
        },
        transactionRevenue: {
          l: 'Revenue',
          g: 'Conversions'
        },
        transactionShipping: {
          l: 'Shipping',
          g: 'Conversions'
        },
        transactionTax: {
          l: 'Tax',
          g: 'Conversions'
        },
        transactions: {
          l: 'Transactions',
          g: 'Conversions'
        },
        transactionsPerVisit: {
          l: 'Ecommerce Conversion Rate',
          g: 'Conversions'
        },
        uniqueAppviews: {
          l: 'Unique Screen Views',
          g: 'Visitors'
        },
        uniquePageviews: {
          l: 'Unique Pageviews',
          g: 'Visitors'
        },
        uniquePurchases: {
          l: 'Unique Purchases',
          g: 'Conversions'
        },
        uniqueSocialInteractions: {
          l: 'Unique Social Actions',
          g: 'Social'
        },
        userTiming: {
          l: 'User Timing (ms)',
          g: 'Content'
        },
        userTimingCount: {
          l: 'User Timing Sample',
          g: 'Content'
        },
        visits: {
          l: 'Visits',
          g: 'Visitors'
        }
      },
      dimensions: {
        adContent: {
          l: 'Ad Content',
          g: 'Advertising'
        },
        adDistributionNetwork: {
          l: 'Ad Distribution Network',
          g: 'Advertising'
        },
        adGroup: {
          l: 'Ad Group',
          g: 'Advertising'
        },
        appId: {
          l: 'App ID',
          g: 'Content'
        },
        appInstallerId: {
          l: 'App Installer ID',
          g: 'Content'
        },
        appName: {
          l: 'App Name',
          g: 'Content'
        },
        appVersion: {
          l: 'App Version',
          g: 'Content'
        },
        appviewDepth: {
          l: 'Screen Depth',
          g: 'Content'
        },
        browser: {
          l: 'Browser',
          g: 'Visitors'
        },
        browserVersion: {
          l: 'Browser Version',
          g: 'Visitors'
        },
        campaign: {
          l: 'Campaign',
          g: 'Advertising'
        },
        campaignCode: {
          l: 'Campaign Code',
          g: 'Advertising'
        },
        city: {
          l: 'City',
          g: 'Visitors'
        },
        connectionSpeed: {
          l: 'Connection Speed',
          g: 'Other'
        },
        contentDescription: {
          l: 'Screen Name',
          g: 'Content'
        },
        contentDomain: {
          l: 'Placement Domain',
          g: 'Advertising'
        },
        contentPlacementType: {
          l: 'Placement Type',
          g: 'Advertising'
        },
        contentUrl: {
          l: 'Placement URL',
          g: 'Advertising'
        },
        continent: {
          l: 'Continent',
          g: 'Visitors'
        },
        countOfVisits: {
          l: 'Count of Visits',
          g: 'Visitors'
        },
        country: {
          l: 'Country / Territory',
          g: 'Visitors'
        },
        customVarName1: {
          l: 'Custom Variable (Key 1)',
          g: 'Custom Variables'
        },
        customVarName2: {
          l: 'Custom Variable (Key 2)',
          g: 'Custom Variables'
        },
        customVarName3: {
          l: 'Custom Variable (Key 3)',
          g: 'Custom Variables'
        },
        customVarName4: {
          l: 'Custom Variable (Key 4)',
          g: 'Custom Variables'
        },
        customVarName5: {
          l: 'Custom Variable (Key 5)',
          g: 'Custom Variables'
        },
        customVarValue1: {
          l: 'Custom Variable (Value 01)',
          g: 'Custom Variables'
        },
        customVarValue2: {
          l: 'Custom Variable (Value 02)',
          g: 'Custom Variables'
        },
        customVarValue3: {
          l: 'Custom Variable (Value 03)',
          g: 'Custom Variables'
        },
        customVarValue4: {
          l: 'Custom Variable (Value 04)',
          g: 'Custom Variables'
        },
        customVarValue5: {
          l: 'Custom Variable (Value 05)',
          g: 'Custom Variables'
        },
        date: {
          l: 'Date',
          g: 'Other'
        },
        dateHour: {
          l: 'Hour of Day',
          g: 'Other'
        },
        dayOfWeek: {
          l: 'Day of week',
          g: 'Other'
        },
        dayOfWeekName: {
          l: 'Day of week name',
          g: 'Other'
        },
        daysSinceLastVisit: {
          l: 'Days Since Last Visit',
          g: 'Visitors'
        },
        destinationUrl: {
          l: 'Destination URL',
          g: 'Advertising'
        },
        deviceCategory: {
          l: 'Device Category',
          g: 'Visitors'
        },
        dma: {
          l: 'Metro',
          g: 'Visitors'
        },
        exitContentDescription: {
          l: 'Exit Screen',
          g: 'Content'
        },
        exitPagePath: {
          l: 'Exit Page',
          g: 'Content'
        },
        flashVersion: {
          l: 'Flash Version',
          g: 'Visitors'
        },
        fullReferrer: {
          l: 'Full Referrer',
          g: 'Content'
        },
        hasSocialSourceReferral: {
          l: 'Social Source Referral',
          g: 'Social'
        },
        hostname: {
          l: 'Hostname',
          g: 'Content'
        },
        hour: {
          l: 'Hour',
          g: 'Other'
        },
        isMobile: {
          l: 'Mobile (Including Tablet)',
          g: 'Visitors'
        },
        javaEnabled: {
          l: 'Java Support',
          g: 'Visitors'
        },
        keyword: {
          l: 'Keyword',
          g: 'Advertising'
        },
        landingContentDescription: {
          l: 'Landing Screen',
          g: 'Content'
        },
        landingPagePath: {
          l: 'Landing Page',
          g: 'Content'
        },
        language: {
          l: 'Language',
          g: 'Visitors'
        },
        matchType: {
          l: 'Query Match Type',
          g: 'Advertising'
        },
        medium: {
          l: 'Medium',
          g: 'Traffic Sources'
        },
        mobileDeviceBranding: {
          l: 'Mobile Device Branding',
          g: 'Visitors'
        },
        mobileDeviceInfo: {
          l: 'Mobile Device Info',
          g: 'Visitors'
        },
        mobileDeviceMarketingName: {
          l: 'Mobile Device Marketing Name',
          g: 'Visitors'
        },
        mobileDeviceModel: {
          l: 'Mobile Device Model',
          g: 'Visitors'
        },
        mobileInputSelector: {
          l: 'Mobile Input Selector',
          g: 'Visitors'
        },
        networkDomain: {
          l: 'Network Domain',
          g: 'Visitors'
        },
        networkLocation: {
          l: 'Service Provider',
          g: 'Visitors'
        },
        nextPagePath: {
          l: 'Next Page Path',
          g: 'Content'
        },
        operatingSystem: {
          l: 'Operating System',
          g: 'Visitors'
        },
        operatingSystemVersion: {
          l: 'Operating System Version',
          g: 'Visitors'
        },
        originatingSocialNetwork: {
          l: 'Social Network',
          g: 'Social'
        },
        pageDepth: {
          l: 'Page Depth',
          g: 'Content'
        },
        pagePath: {
          l: 'Page',
          g: 'Content'
        },
        pagePathLevel1: {
          l: 'Page path level 1',
          g: 'Content'
        },
        pagePathLevel2: {
          l: 'Page path level 2',
          g: 'Content'
        },
        pagePathLevel3: {
          l: 'Page path level 3',
          g: 'Content'
        },
        pagePathLevel4: {
          l: 'Page path level 4',
          g: 'Content'
        },
        pageTitle: {
          l: 'Page Title',
          g: 'Content'
        },
        previousPagePath: {
          l: 'Previous Page Path',
          g: 'Content'
        },
        query: {
          l: 'Matched Search Query',
          g: 'Advertising'
        },
        referralPath: {
          l: 'Referral Path',
          g: 'Traffic Sources'
        },
        region: {
          l: 'Region',
          g: 'Visitors'
        },
        screenColors: {
          l: 'Screen Colors',
          g: 'Visitors'
        },
        screenResolution: {
          l: 'Screen Resolution',
          g: 'Visitors'
        },
        searchCategory: {
          l: 'Site Search Category',
          g: 'Content'
        },
        searchDestinationPage: {
          l: 'Destination Page',
          g: 'Content'
        },
        searchKeyword: {
          l: 'Search Term',
          g: 'Content'
        },
        searchKeywordRefinement: {
          l: 'Refined Keyword',
          g: 'Content'
        },
        searchStartPage: {
          l: 'Start Page',
          g: 'Content'
        },
        searchUsed: {
          l: 'Site Search Status',
          g: 'Content'
        },
        socialAction: {
          l: 'Social Action',
          g: 'Social'
        },
        socialContentURL: {
          l: 'Shared URL',
          g: 'Social'
        },
        socialEngagementType: {
          l: 'Social Type',
          g: 'Social'
        },
        socialNetwork: {
          l: 'Social Source',
          g: 'Social'
        },
        socialNetworkAction: {
          l: 'Social Source and Action',
          g: 'Social'
        },
        socialNetworkActionVisit: {
          l: 'Social Source and Action',
          g: 'Social'
        },
        socialTarget: {
          l: 'Social Entity',
          g: 'Social'
        },
        source: {
          l: 'Source',
          g: 'Traffic Sources'
        },
        sourceMedium: {
          l: 'Source / Medium',
          g: 'Traffic Sources'
        },
        subContinent: {
          l: 'Sub Continent Region',
          g: 'Visitors'
        },
        trafficType: {
          l: 'Traffic Type',
          g: 'Traffic Sources'
        },
        userDefinedValue: {
          l: 'User Defined Value',
          g: 'Content'
        },
        userTimingCategory: {
          l: 'Timing Category',
          g: 'Content'
        },
        userTimingLabel: {
          l: 'Timing Label',
          g: 'Content'
        },
        userTimingVariable: {
          l: 'Timing Variable',
          g: 'Content'
        },
        visitorType: {
          l: 'Visitor Type',
          g: 'Visitors'
        },
        yearMonth: {
          l: 'Month of Year',
          g: 'Other'
        },
        yearWeek: {
          l: 'Week of Year',
          g: 'Other'
        }
      }
    };

    return MoreAnalyticsL10N;

  })();

}).call(this);
