jQuery.MoreAnalyticsL10N = class MoreAnalyticsL10N
  @lexicon: {
    metrics:{
      abandonedFunnels:{l:'目標到達プロセスの放棄数',g:'その他'},
      abandonedFunnels1:{l:'目標 1（目標 1 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels10:{l:'目標 10（目標 10 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels11:{l:'目標 11（目標 11 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels12:{l:'目標 12（目標 12 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels13:{l:'目標 13（目標 13 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels14:{l:'目標 14（目標 14 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels15:{l:'目標 15（目標 15 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels16:{l:'目標 16（目標 16 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels17:{l:'目標 17（目標 17 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels18:{l:'目標 18（目標 18 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels19:{l:'目標 19（目標 19 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels2:{l:'目標 2（目標 2 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels20:{l:'目標 20（目標 20 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels3:{l:'目標 3（目標 3 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels4:{l:'目標 4（目標 4 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels5:{l:'目標 5（目標 5 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels6:{l:'目標 6（目標 6 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels7:{l:'目標 7（目標 7 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels8:{l:'目標 8（目標 8 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnels9:{l:'目標 9（目標 9 到達プロセスの放棄数）',g:'その他'},
      abandonedFunnelsRate:{l:'目標全体の放棄率',g:'その他'},
      abandonedFunnelsRate1:{l:'目標 1（目標 1 の放棄率）',g:'その他'},
      abandonedFunnelsRate10:{l:'目標 10（目標 10 の放棄率）',g:'その他'},
      abandonedFunnelsRate11:{l:'目標 11（目標 11 の放棄率）',g:'その他'},
      abandonedFunnelsRate12:{l:'目標 12（目標 12 の放棄率）',g:'その他'},
      abandonedFunnelsRate13:{l:'目標 13（目標 13 の放棄率）',g:'その他'},
      abandonedFunnelsRate14:{l:'目標 14（目標 14 の放棄率）',g:'その他'},
      abandonedFunnelsRate15:{l:'目標 15（目標 15 の放棄率）',g:'その他'},
      abandonedFunnelsRate16:{l:'目標 16（目標 16 の放棄率）',g:'その他'},
      abandonedFunnelsRate17:{l:'目標 17（目標 17 の放棄率）',g:'その他'},
      abandonedFunnelsRate18:{l:'目標 18（目標 18 の放棄率）',g:'その他'},
      abandonedFunnelsRate19:{l:'目標 19（目標 19 の放棄率）',g:'その他'},
      abandonedFunnelsRate2:{l:'目標 2（目標 2 の放棄率）',g:'その他'},
      abandonedFunnelsRate20:{l:'目標 20（目標 20 の放棄率）',g:'その他'},
      abandonedFunnelsRate3:{l:'目標 3（目標 3 の放棄率）',g:'その他'},
      abandonedFunnelsRate4:{l:'目標 4（目標 4 の放棄率）',g:'その他'},
      abandonedFunnelsRate5:{l:'目標 5（目標 5 の放棄率）',g:'その他'},
      abandonedFunnelsRate6:{l:'目標 6（目標 6 の放棄率）',g:'その他'},
      abandonedFunnelsRate7:{l:'目標 7（目標 7 の放棄率）',g:'その他'},
      abandonedFunnelsRate8:{l:'目標 8（目標 8 の放棄率）',g:'その他'},
      abandonedFunnelsRate9:{l:'目標 9（目標 9 の放棄率）',g:'その他'},
      adsenseAdUnitsViewed:{l:'表示された AdSense 広告ユニット',g:'広告'},
      adsenseAdsClicked:{l:'クリックされた AdSense 広告',g:'広告'},
      adsenseCTR:{l:'AdSense クリック率',g:'広告'},
      adsenseECPM:{l:'AdSense 有効 CPM',g:'広告'},
      adsenseExits:{l:'AdSense の離脱数',g:'広告'},
      adsensePageImpressions:{l:'AdSense のページ表示回数',g:'広告'},
      adsenseRevenue:{l:'AdSense の収益',g:'広告'},
      adsenseUnitImpressions:{l:'表示された AdSense 広告',g:'広告'},
      appviews:{l:'スクリーン ビュー',g:'ユーザー'},
      avgAppviewDuration:{l:'スクリーンの平均滞在時間',g:'ユーザー'},
      avgAppviews:{l:'セッション別スクリーン数',g:'ユーザー'},
      avgDomContentLoadedTime:{l:'平均ドキュメント コンテンツ読み込み時間（秒）',g:'コンテンツ'},
      avgDomInteractiveTime:{l:'平均ドキュメント インタラクティブ時間（秒）',g:'コンテンツ'},
      avgDomainLookupTime:{l:'ドメインの平均ルックアップ時間（秒）',g:'コンテンツ'},
      avgPageDownloadTime:{l:'ページの平均ダウンロード時間（秒）',g:'コンテンツ'},
      avgPageDuration:{l:'平均ページ滞在時間',g:'ユーザー'},
      avgPageLoadTime:{l:'平均表示時間（秒）',g:'コンテンツ'},
      avgPageviews:{l:'訪問別ページビュー',g:'ユーザー'},
      avgRedirectionTime:{l:'平均リダイレクト時間（秒）',g:'コンテンツ'},
      avgServerConnectionTime:{l:'サーバーの平均接続時間（秒）',g:'コンテンツ'},
      avgServerResponseTime:{l:'サーバーの平均応答時間（秒）',g:'コンテンツ'},
      avgSessionTime:{l:'訪問時の平均滞在時間',g:'ユーザー'},
      avgUserTiming:{l:'平均のユーザー設定速度（秒）',g:'コンテンツ'},
      bounceRate:{l:'直帰率',g:'ユーザー'},
      bounces:{l:'直帰数',g:'ユーザー'},
      domLatencyMetricsCount:{l:'DOM 経過時間サンプル',g:'コンテンツ'},
      domainLookupTimeCount:{l:'ドメイン ルックアップのサンプル',g:'コンテンツ'},
      entranceRate:{l:'閲覧開始数/ページビュー数',g:'コンテンツ'},
      entrances:{l:'閲覧開始数',g:'コンテンツ'},
      eventAvgValue:{l:'平均値',g:'コンテンツ'},
      eventValue:{l:'イベントの値',g:'コンテンツ'},
      exitRate:{l:'離脱率',g:'ユーザー'},
      exits:{l:'離脱数',g:'ユーザー'},
      goal10Completions:{l:'目標 10（目標 10 の完了数）',g:'コンバージョン'},
      goal10Starts:{l:'目標 10（目標 10 の開始）',g:'コンバージョン'},
      goal10Value:{l:'目標 10（目標 10 の値）',g:'コンバージョン'},
      goal11Completions:{l:'目標 11（目標 11 の完了数）',g:'コンバージョン'},
      goal11Starts:{l:'目標 11（目標 11 の開始）',g:'コンバージョン'},
      goal11Value:{l:'目標 11（目標 11 の値）',g:'コンバージョン'},
      goal12Completions:{l:'目標 12（目標 12 の完了数）',g:'コンバージョン'},
      goal12Starts:{l:'目標 12（目標 12 の開始）',g:'コンバージョン'},
      goal12Value:{l:'目標 12（目標 12 の値）',g:'コンバージョン'},
      goal13Completions:{l:'目標 13（目標 13 の完了数）',g:'コンバージョン'},
      goal13Starts:{l:'目標 13（目標 13 の開始）',g:'コンバージョン'},
      goal13Value:{l:'目標 13（目標 13 の値）',g:'コンバージョン'},
      goal14Completions:{l:'目標 14（目標 14 の完了数）',g:'コンバージョン'},
      goal14Starts:{l:'目標 14（目標 14 の開始）',g:'コンバージョン'},
      goal14Value:{l:'目標 14（目標 14 の値）',g:'コンバージョン'},
      goal15Completions:{l:'目標 15（目標 15 の完了数）',g:'コンバージョン'},
      goal15Starts:{l:'目標 15（目標 15 の開始）',g:'コンバージョン'},
      goal15Value:{l:'目標 15（目標 15 の値）',g:'コンバージョン'},
      goal16Completions:{l:'目標 16（目標 16 の完了数）',g:'コンバージョン'},
      goal16Starts:{l:'目標 16（目標 16 の開始）',g:'コンバージョン'},
      goal16Value:{l:'目標 16（目標 16 の値）',g:'コンバージョン'},
      goal17Completions:{l:'目標 17（目標 17 の完了数）',g:'コンバージョン'},
      goal17Starts:{l:'目標 17（目標 17 の開始）',g:'コンバージョン'},
      goal17Value:{l:'目標 17（目標 17 の値）',g:'コンバージョン'},
      goal18Completions:{l:'目標 18（目標 18 の完了数）',g:'コンバージョン'},
      goal18Starts:{l:'目標 18（目標 18 の開始）',g:'コンバージョン'},
      goal18Value:{l:'目標 18（目標 18 の値）',g:'コンバージョン'},
      goal19Completions:{l:'目標 19（目標 19 の完了数）',g:'コンバージョン'},
      goal19Starts:{l:'目標 19（目標 19 の開始）',g:'コンバージョン'},
      goal19Value:{l:'目標 19（目標 19 の値）',g:'コンバージョン'},
      goal1Completions:{l:'目標 1（目標 1 の完了数）',g:'コンバージョン'},
      goal1Starts:{l:'目標 1（目標 1 の開始）',g:'コンバージョン'},
      goal1Value:{l:'目標 1（目標 1 の値）',g:'コンバージョン'},
      goal20Completions:{l:'目標 20（目標 20 の完了数）',g:'コンバージョン'},
      goal20Starts:{l:'目標 20（目標 20 の開始）',g:'コンバージョン'},
      goal20Value:{l:'目標 20（目標 20 の値）',g:'コンバージョン'},
      goal2Completions:{l:'目標 2（目標 2 の完了数）',g:'コンバージョン'},
      goal2Starts:{l:'目標 2（目標 2 の開始）',g:'コンバージョン'},
      goal2Value:{l:'目標 2（目標 2 の値）',g:'コンバージョン'},
      goal3Completions:{l:'目標 3（目標 3 の完了数）',g:'コンバージョン'},
      goal3Starts:{l:'目標 3（目標 3 の開始）',g:'コンバージョン'},
      goal3Value:{l:'目標 3（目標 3 の値）',g:'コンバージョン'},
      goal4Completions:{l:'目標 4（目標 4 の完了数）',g:'コンバージョン'},
      goal4Starts:{l:'目標 4（目標 4 の開始）',g:'コンバージョン'},
      goal4Value:{l:'目標 4（目標 4 の値）',g:'コンバージョン'},
      goal5Completions:{l:'目標 5（目標 5 の完了数）',g:'コンバージョン'},
      goal5Starts:{l:'目標 5（目標 5 の開始）',g:'コンバージョン'},
      goal5Value:{l:'目標 5（目標 5 の値）',g:'コンバージョン'},
      goal6Completions:{l:'目標 6（目標 6 の完了数）',g:'コンバージョン'},
      goal6Starts:{l:'目標 6（目標 6 の開始）',g:'コンバージョン'},
      goal6Value:{l:'目標 6（目標 6 の値）',g:'コンバージョン'},
      goal7Completions:{l:'目標 7（目標 7 の完了数）',g:'コンバージョン'},
      goal7Starts:{l:'目標 7（目標 7 の開始）',g:'コンバージョン'},
      goal7Value:{l:'目標 7（目標 7 の値）',g:'コンバージョン'},
      goal8Completions:{l:'目標 8（目標 8 の完了数）',g:'コンバージョン'},
      goal8Starts:{l:'目標 8（目標 8 の開始）',g:'コンバージョン'},
      goal8Value:{l:'目標 8（目標 8 の値）',g:'コンバージョン'},
      goal9Completions:{l:'目標 9（目標 9 の完了数）',g:'コンバージョン'},
      goal9Starts:{l:'目標 9（目標 9 の開始）',g:'コンバージョン'},
      goal9Value:{l:'目標 9（目標 9 の値）',g:'コンバージョン'},
      goalCompletionsAll:{l:'目標の完了数',g:'コンバージョン'},
      goalConversionRate:{l:'コンバージョン率',g:'コンバージョン'},
      goalConversionRate1:{l:'目標 1（目標 1 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate10:{l:'目標 10（目標 10 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate11:{l:'目標 11（目標 11 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate12:{l:'目標 12（目標 12 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate13:{l:'目標 13（目標 13 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate14:{l:'目標 14（目標 14 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate15:{l:'目標 15（目標 15 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate16:{l:'目標 16（目標 16 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate17:{l:'目標 17（目標 17 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate18:{l:'目標 18（目標 18 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate19:{l:'目標 19（目標 19 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate2:{l:'目標 2（目標 2 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate20:{l:'目標 20（目標 20 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate3:{l:'目標 3（目標 3 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate4:{l:'目標 4（目標 4 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate5:{l:'目標 5（目標 5 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate6:{l:'目標 6（目標 6 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate7:{l:'目標 7（目標 7 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate8:{l:'目標 8（目標 8 のコンバージョン率）',g:'コンバージョン'},
      goalConversionRate9:{l:'目標 9（目標 9 のコンバージョン率）',g:'コンバージョン'},
      goalStartsAll:{l:'目標の開始数',g:'コンバージョン'},
      goalValueAll:{l:'目標値',g:'コンバージョン'},
      goalValuePerVisit:{l:'平均目標値',g:'コンバージョン'},
      itemLocalRevenue:{l:'ローカルの商品の収益',g:'コンバージョン'},
      itemQuantity:{l:'数量',g:'コンバージョン'},
      itemRevenue:{l:'商品の収益',g:'コンバージョン'},
      latencyMetricsCount:{l:'速度指標のサンプル',g:'コンテンツ'},
      margin:{l:'利益率',g:'広告'},
      newVisits:{l:'新規訪問数',g:'ユーザー'},
      pageDownloadTimeCount:{l:'ページ ダウンロードのサンプル',g:'コンテンツ'},
      pageLoadTimeCount:{l:'サンプル数',g:'コンテンツ'},
      pageValue:{l:'ページの価値',g:'コンバージョン'},
      pageviews:{l:'ページビュー数',g:'ユーザー'},
      pageviewsPerSearch:{l:'結果のページビュー数/検索',g:'ユーザー'},
      percentNewVisits:{l:'新規訪問の割合',g:'ユーザー'},
      percentSearchExits:{l:'検索による離脱数の割合',g:'ユーザー'},
      percentSearchRefinements:{l:'再検索数の割合',g:'ユーザー'},
      productRevenuePerProducts:{l:'平均価格',g:'コンバージョン'},
      productsPerProductPurchases:{l:'平均数量',g:'コンバージョン'},
      redirectionTimeCount:{l:'リダイレクトのサンプル',g:'コンテンツ'},
      returnOnInvestment:{l:'投資収益率',g:'広告'},
      revenuePerClick:{l:'収益単価',g:'広告'},
      revenuePerTransaction:{l:'平均値',g:'コンバージョン'},
      revenuePerVisit:{l:'平均訪問単価',g:'コンバージョン'},
      searchDepth:{l:'検索深度',g:'コンテンツ'},
      searchDuration:{l:'検索後の時間',g:'コンテンツ'},
      searchExits:{l:'検索結果の離脱',g:'コンテンツ'},
      searchRefinements:{l:'再検索数',g:'コンテンツ'},
      searchUniques:{l:'検索回数の合計',g:'ユーザー'},
      searchVisits:{l:'検索による訪問',g:'コンテンツ'},
      serverConnectionTimeCount:{l:'サーバー接続のサンプル',g:'コンテンツ'},
      serverResponseTimeCount:{l:'サーバー応答のサンプル',g:'コンテンツ'},
      socialInteractions:{l:'アクション',g:'ソーシャル'},
      socialInteractionsPerVisit:{l:'訪問あたりのアクション',g:'ソーシャル'},
      timeOnAppview:{l:'スクリーン滞在時間',g:'コンテンツ'},
      timeOnPage:{l:'ページ滞在時間',g:'コンテンツ'},
      timeOnSite:{l:'訪問の滞在時間',g:'ユーザー'},
      totalEvents:{l:'合計イベント数',g:'コンテンツ'},
      totalVisitors:{l:'ユーザー数',g:'ユーザー'},
      transactionLocalRevenue:{l:'ローカルの収益',g:'コンバージョン'},
      transactionLocalShipping:{l:'ローカルの配送料',g:'コンバージョン'},
      transactionLocalTax:{l:'ローカルの税金',g:'コンバージョン'},
      transactionRevenue:{l:'収益',g:'コンバージョン'},
      transactionShipping:{l:'配送',g:'コンバージョン'},
      transactionTax:{l:'税金',g:'コンバージョン'},
      transactions:{l:'トランザクション数',g:'コンバージョン'},
      transactionsPerVisit:{l:'e コマースのコンバージョン率',g:'コンバージョン'},
      uniqueAppviews:{l:'ユニーク スクリーン ビュー',g:'ユーザー'},
      uniqueEvents:{l:'ユニーク イベント数',g:'コンテンツ'},
      uniquePageviews:{l:'ページ別訪問数',g:'ユーザー'},
      uniquePurchases:{l:'固有の購入数',g:'コンバージョン'},
      uniqueSocialInteractions:{l:'ユニーク アクション',g:'ソーシャル'},
      userTiming:{l:'ユーザー設定速度（ミリ秒）',g:'コンテンツ'},
      userTimingCount:{l:'ユーザー設定速度のサンプル',g:'コンテンツ'},
      visits:{l:'訪問数',g:'ユーザー'}
    },
    dimensions:{
      adContent:{l:'広告のコンテンツ',g:'広告'},
      adDistributionNetwork:{l:'広告掲載ネットワーク',g:'広告'},
      adGroup:{l:'広告グループ',g:'広告'},
      adSlot:{l:'広告スロット',g:'広告'},
      adSlotPosition:{l:'広告スロット位置',g:'広告'},
      affiliation:{l:'アフィリエーション',g:'コンバージョン'},
      appId:{l:'アプリケーション ID',g:'コンテンツ'},
      appInstallerId:{l:'アプリケーション インストーラ ID',g:'コンテンツ'},
      appName:{l:'アプリ名',g:'コンテンツ'},
      appVersion:{l:'アプリのバージョン',g:'コンテンツ'},
      appviewDepth:{l:'訪問時のスクリーン数',g:'コンテンツ'},
      browser:{l:'ブラウザ',g:'ユーザー'},
      browserVersion:{l:'ブラウザのバージョン',g:'ユーザー'},
      campaign:{l:'キャンペーン',g:'広告'},
      campaignCode:{l:'キャンペーン コード',g:'広告'},
      city:{l:'市区町村',g:'ユーザー'},
      clickSocialAnnotationType:{l:'+1 情報の種類',g:'広告'},
      connectionSpeed:{l:'接続速度',g:'その他'},
      contentDescription:{l:'スクリーン名',g:'コンテンツ'},
      contentDomain:{l:'プレースメントのドメイン',g:'広告'},
      contentPlacementType:{l:'プレースメント タイプ',g:'広告'},
      contentUrl:{l:'プレースメント URL',g:'広告'},
      continent:{l:'大陸',g:'ユーザー'},
      countOfVisits:{l:'リピートの回数',g:'ユーザー'},
      countOfVisitsToATransaction:{l:'購入までの訪問数',g:'コンバージョン'},
      country:{l:'国/地域',g:'ユーザー'},
      currencyCode:{l:'通貨コード',g:'コンバージョン'},
      customVarName1:{l:'カスタム変数（キー 1）',g:'カスタム変数'},
      customVarName2:{l:'カスタム変数（キー 2）',g:'カスタム変数'},
      customVarName3:{l:'カスタム変数（キー 3）',g:'カスタム変数'},
      customVarName4:{l:'カスタム変数（キー 4）',g:'カスタム変数'},
      customVarName5:{l:'カスタム変数（キー 5）',g:'カスタム変数'},
      customVarValue1:{l:'カスタム変数（値 01）',g:'カスタム変数'},
      customVarValue2:{l:'カスタム変数（値 02）',g:'カスタム変数'},
      customVarValue3:{l:'カスタム変数（値 03）',g:'カスタム変数'},
      customVarValue4:{l:'カスタム変数（値 04）',g:'カスタム変数'},
      customVarValue5:{l:'カスタム変数（値 05）',g:'カスタム変数'},
      date:{l:'日付',g:'その他'},
      dateHour:{l:'時間帯',g:'その他'},
      dayOfWeek:{l:'曜日',g:'その他'},
      dayOfWeekName:{l:'曜日の名前',g:'その他'},
      daysSinceLastVisit:{l:'リピートの間隔',g:'ユーザー'},
      daysToTransaction:{l:'購入までの日数',g:'コンバージョン'},
      destinationUrl:{l:'リンク先 URL',g:'広告'},
      deviceCategory:{l:'デバイス カテゴリ',g:'ユーザー'},
      dma:{l:'大都市圏',g:'ユーザー'},
      eventAction:{l:'イベント アクション',g:'コンテンツ'},
      eventCategory:{l:'イベント カテゴリ',g:'コンテンツ'},
      eventLabel:{l:'イベント ラベル',g:'コンテンツ'},
      exitContentDescription:{l:'離脱スクリーン',g:'コンテンツ'},
      exitPagePath:{l:'離脱ページ',g:'コンテンツ'},
      flashVersion:{l:'Flash のバージョン',g:'ユーザー'},
      fullReferrer:{l:'完全なリファラー',g:'コンテンツ'},
      hasSocialSourceReferral:{l:'ソーシャル メディアからの参照',g:'ソーシャル'},
      hostname:{l:'ホスト名',g:'コンテンツ'},
      hour:{l:'時',g:'その他'},
      isMobile:{l:'モバイル（タブレットを含む）',g:'ユーザー'},
      javaEnabled:{l:'Java サポート',g:'ユーザー'},
      keyword:{l:'キーワード',g:'広告'},
      landingContentDescription:{l:'ランディング スクリーン',g:'コンテンツ'},
      landingPagePath:{l:'ランディング ページ',g:'コンテンツ'},
      language:{l:'言語',g:'ユーザー'},
      matchType:{l:'クエリのマッチ タイプ',g:'広告'},
      medium:{l:'メディア',g:'トラフィック'},
      mobileDeviceBranding:{l:'携帯端末ブランド',g:'ユーザー'},
      mobileDeviceInfo:{l:'携帯端末の情報',g:'ユーザー'},
      mobileDeviceMarketingName:{l:'携帯端末のマーケティング名',g:'ユーザー'},
      mobileDeviceModel:{l:'携帯端末モデル',g:'ユーザー'},
      mobileInputSelector:{l:'モバイル入力セレクタ',g:'ユーザー'},
      networkDomain:{l:'ネットワーク ドメイン',g:'ユーザー'},
      networkLocation:{l:'サービス プロバイダ',g:'ユーザー'},
      nextPagePath:{l:'次のページ遷移',g:'コンテンツ'},
      operatingSystem:{l:'オペレーティング システム',g:'ユーザー'},
      operatingSystemVersion:{l:'OS のバージョン',g:'ユーザー'},
      originatingSocialNetwork:{l:'ソーシャル ネットワーク',g:'ソーシャル'},
      pageDepth:{l:'訪問時のページ数',g:'コンテンツ'},
      pagePath:{l:'ページ',g:'コンテンツ'},
      pagePathLevel1:{l:'第 1 階層',g:'コンテンツ'},
      pagePathLevel2:{l:'第 2 階層',g:'コンテンツ'},
      pagePathLevel3:{l:'第 3 階層',g:'コンテンツ'},
      pagePathLevel4:{l:'第 4 階層',g:'コンテンツ'},
      pageTitle:{l:'ページ タイトル',g:'コンテンツ'},
      previousPagePath:{l:'前のページ遷移',g:'コンテンツ'},
      query:{l:'一致した検索クエリ',g:'広告'},
      referralPath:{l:'参照 URL',g:'トラフィック'},
      region:{l:'地域',g:'ユーザー'},
      screenColors:{l:'画面の色',g:'ユーザー'},
      screenResolution:{l:'画面の解像度',g:'ユーザー'},
      searchCategory:{l:'サイト内検索のカテゴリ',g:'コンテンツ'},
      searchDestinationPage:{l:'リンク先ページ',g:'コンテンツ'},
      searchKeyword:{l:'検索クエリ',g:'コンテンツ'},
      searchKeywordRefinement:{l:'再検索キーワード',g:'コンテンツ'},
      searchStartPage:{l:'開始ページ',g:'コンテンツ'},
      searchUsed:{l:'サイト内検索のステータス',g:'コンテンツ'},
      socialAction:{l:'ソーシャル アクション',g:'ソーシャル'},
      socialContentURL:{l:'共有された URL',g:'ソーシャル'},
      socialEngagementType:{l:'ソーシャル タイプ',g:'ソーシャル'},
      socialNetwork:{l:'ソーシャル メディア',g:'ソーシャル'},
      socialNetworkAction:{l:'ソーシャル メディアとアクション',g:'ソーシャル'},
      socialNetworkActionVisit:{l:'ソーシャル メディアとアクション',g:'ソーシャル'},
      socialTarget:{l:'エンティティ',g:'ソーシャル'},
      source:{l:'参照元',g:'トラフィック'},
      sourceMedium:{l:'参照元/メディア',g:'トラフィック'},
      subContinent:{l:'亜大陸',g:'ユーザー'},
      trafficType:{l:'トラフィックの種類',g:'トラフィック'},
      transactionId:{l:'トランザクション',g:'コンバージョン'},
      userDefinedValue:{l:'ユーザー定義値',g:'コンテンツ'},
      userTimingCategory:{l:'速度のカテゴリ',g:'コンテンツ'},
      userTimingLabel:{l:'速度のラベル',g:'コンテンツ'},
      userTimingVariable:{l:'速度の変数',g:'コンテンツ'},
      visitorType:{l:'ユーザーの種類',g:'ユーザー'},
      yearMonth:{l:'月（年間）',g:'その他'},
      yearWeek:{l:'週（年間）',g:'その他'}
    }
  }